libunwind
Sphinx
python3-Pygments
MarkupSafe
python3-Jinja2
alabaster
imagesize
snowballstemmer
python-certifi
python-chardet
python-urllib3
idna
python-requests
python3-pyparsing
python3-six
python3-packaging
sphinxcontrib-applehelp
sphinxcontrib-devhelp
sphinxcontrib-htmlhelp
sphinxcontrib-jsmath
sphinxcontrib-qthelp
sphinxcontrib-serializinghtml
pytz
python3-babel
Sphinx
libc++
discord
